{% set name = "natcap.invest" %}
{% set version = "3.17.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace(".", "_") }}-{{ version }}.tar.gz
  sha256: d374b9759a0df782c0c59128cb92eb485b3ff3b87e5296987589e76e85db0d62

build:
  skip: true  # [py==37]
  number: 0
  script_env:
    - NATCAP_INVEST_GDAL_LIB_PATH={{ CONDA_PREFIX }}/Library
  script:
    - {{ PYTHON }} -m build --wheel --no-isolation -x
    - {{ PYTHON }} -m build --sdist --no-isolation -x
    - {{ PYTHON }} -m pip install --no-deps --no-index --only-binary natcap.invest --find-links=dist "natcap.invest=={{ version }}"
  entry_points:
    - invest = natcap.invest.cli:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >3.0.0                          # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - babel
    - cython >3.0.0
    - libgdal-core <3.11  # for compatibility with rasterio, which doesn't yet support gdal 3.11
    - numpy
    - setuptools_scm
    - setuptools >=77.0  # For PEP 639 license syntax update
    - wheel
    - python-build
  run:
    - python
    - libsqlite !=3.49.1  # https://github.com/conda-forge/sqlite-feedstock/issues/130
    - sqlite !=3.49.1     # https://github.com/conda-forge/sqlite-feedstock/issues/130
    - babel
    - chardet >=3.0.4
    - cython >3.0.0
    - docutils
    - flask
    - flask-cors
    - geometamaker
    - numpy >=1.11.0,!=1.16.0
    - pandas >=1.2.1
    - pint
    - psutil >=5.6.6
    - pygeoprocessing >=2.4.6
    - pyro5
    - requests
    - rtree >=0.8.2,!=0.9.1
    - scipy >=1.9.0
    - shapely >=2.0.0
    - taskgraph >=0.11.0

test:
  imports:
    - natcap.invest
  requires:
    - pip
  commands:
    - pip check
    - invest list

about:
  home: https://github.com/natcap/invest
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'InVEST: models that map and value the goods and services from nature that sustain and fulfill human life.'
  description: |
    InVEST (Integrated Valuation of Ecosystem Services and Tradeoffs) is a family of tools for quantifying the values of natural capital in clear, credible, and practical ways. In promising a return (of societal benefits) on investments in nature, the scientific community needs to deliver knowledge and tools to quantify and forecast this return. InVEST enables decision-makers to quantify the importance of natural capital, to assess the tradeoffs associated with alternative choices, and to integrate conservation and human development.
  doc_url: https://invest.readthedocs.io/
  dev_url: https://github.com/natcap/invest

extra:
  recipe-maintainers:
    - davemfish
    - dcdenu4
    - phargogh
    - davemfish
    - emlys
