{% set name = "natcap.invest" %}
{% set version = "3.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d25bcde6812f0f9ac8c55e6f20c35ba4842ff473f230c470251b6a595a3b81ef

build:
  skip: true  # [py==37]
  number: 1
  script:
    - {{ PYTHON }} -m build --wheel --no-isolation -x
    - {{ PYTHON }} -m build --sdist --no-isolation -x
    - {{ PYTHON }} -m pip install --no-deps --no-index --only-binary natcap.invest --find-links=dist "natcap.invest=={{ version }}"


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - babel
    - cython
    - numpy
    - setuptools_scm
    - setuptools
    - wheel
    - python-build
  run:
    - python
    - babel
    - chardet >=3.0.4
    - cython
    - gdal >=3.4.2
    - flask
    - flask_cors
    - six
    - numpy >=1.11.0,!=1.16.0
    - {{ pin_compatible('numpy') }}
    - openpyxl
    - xlrd
    - pandas >=1.2.1
    - pint
    - psutil >=5.6.6
    - pygeoprocessing >=2.3.2
    - pyro4 ==4.77
    - pyside2 !=5.15.0
    - qtawesome
    - qtpy >1.3
    - requests
    - rtree >=0.8.2,!=0.9.1
    - scipy >=1.9.0
    - shapely >=1.7.1,<1.8.2
    - taskgraph >=0.11.0

test:
  imports:
    - natcap.invest
    - natcap.invest.ui
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/natcap/invest
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'InVEST: models that map and value the goods and services from nature that sustain and fulfill human life.'
  description: |
    InVEST (Integrated Valuation of Ecosystem Services and Tradeoffs) is a family of tools for quantifying the values of natural capital in clear, credible, and practical ways. In promising a return (of societal benefits) on investments in nature, the scientific community needs to deliver knowledge and tools to quantify and forecast this return. InVEST enables decision-makers to quantify the importance of natural capital, to assess the tradeoffs associated with alternative choices, and to integrate conservation and human development.
  doc_url: https://invest.readthedocs.io/
  dev_url: https://github.com/natcap/invest

extra:
  recipe-maintainers:
    - dcdenu4
    - phargogh
    - TnTo
